function XSPlot26p(X1, YMatrix1, dcdsp1, YMatrix2)
%CREATEFIGURE2(X1, YMatrix1, dcdsp1, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  DCDSP1:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 22-Jan-2018 18:18:30

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(loglog1(1),'DisplayName','O^{2+}','Color',[0 0 1]);
set(loglog1(2),'DisplayName','O^{3+}','Color',[1 0 0]);
set(loglog1(3),'DisplayName','O^{4+}','Color',[0 1 0]);
set(loglog1(4),'DisplayName','O^{5+}');
set(loglog1(5),'DisplayName','O^{6+}','Color',[1 0 1]);

% Create multiple lines using matrix input to loglog
loglog2 = loglog(dcdsp1,YMatrix2,'Marker','diamond','LineWidth',2,...
    'LineStyle','none',...
    'Parent',axes1);
set(loglog2(1),'DisplayName','O^{2+}','Color',[0 0 1]);
set(loglog2(2),'DisplayName','O^{3+}','Color',[1 0 0]);
set(loglog2(3),'DisplayName','O^{4+}','Color',[0 1 0]);
set(loglog2(4),'DisplayName','O^{5+}');
set(loglog2(5),'DisplayName','O^{6+}','Color',[1 0 1]);

% Create ylabel
ylabel('Cross-Section [cm^{-2}]','FontWeight','bold');

% Create xlabel
xlabel('Energy [keV/u]','FontWeight','bold');

% Create title
title('[Insert Process Here]');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold','TickDir','both','XMinorTick',...
    'on','XScale','log','YMinorTick','on','YScale','log');
