function XSPlotn18(X1, YMatrix1, sip1, YMatrix2)
%CREATEFIGURE2(X1, YMatrix1, sip1, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  SIP1:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 24-Apr-2018 17:31:56

% Create figure
figure1 = figure('NumberTitle','off','Name','SI');

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'LineWidth',2);
set(loglog1(1),'DisplayName','O^{-}','Color',[0 0 0]);
set(loglog1(2),'DisplayName','O','Color',[1 0 0]);
set(loglog1(3),'DisplayName','O^{+}','Color',[1 0.600000023841858 0]);
set(loglog1(4),'DisplayName','O^{2+}',...
    'Color',[0.800000011920929 0.800000011920929 0]);
set(loglog1(5),'DisplayName','O^{3+}','Color',[0 1 0]);
set(loglog1(6),'DisplayName','O^{4+}','Color',[0 0 1]);
set(loglog1(7),'DisplayName','O^{5+}','Color',[0.600000023841858 0 1]);
set(loglog1(8),'DisplayName','O^{6+}',...
    'Color',[0.600000023841858 0 0.600000023841858]);
set(loglog1(9),'DisplayName','O^{7+}','Color',[1 0 1]);
%set(loglog1(10),'DisplayName','O^{8+}','Color',[0 1 1]);

% Create multiple lines using matrix input to loglog
loglog2 = loglog(sip1,YMatrix2,'MarkerSize',8,'Marker','o','LineWidth',2,...
    'LineStyle','none',...
    'Parent',axes1);
set(loglog2(1),'DisplayName','O^{-}','Color',[0 0 0]);
set(loglog2(2),'DisplayName','O','Color',[1 0 0]);
set(loglog2(3),'DisplayName','O^{+}','Color',[1 0.600000023841858 0]);
set(loglog2(4),'DisplayName','O^{2+}',...
    'Color',[0.800000011920929 0.800000011920929 0]);
set(loglog2(5),'DisplayName','O^{3+}','Color',[0 1 0]);
set(loglog2(6),'DisplayName','O^{4+}','Color',[0 0 1]);
set(loglog2(7),'DisplayName','O^{5+}','Color',[0.600000023841858 0 1]);
set(loglog2(8),'DisplayName','O^{6+}',...
    'Color',[0.600000023841858 0 0.600000023841858]);
set(loglog2(9),'DisplayName','O^{7+}','Color',[1 0 1]);
%set(loglog2(10),'DisplayName','O^{8+}','Color',[0 1 1]);

% Create ylabel
ylabel('Cross-Section [cm^{-2}]','FontWeight','bold');

% Create xlabel
xlabel('Energy [keV/u]','FontWeight','bold');

% Create title
title('SI');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold','TickDir','both','XMinorTick',...
    'on','XScale','log','YMinorTick','on','YScale','log');
% Create textarrow
annotation(figure1,'textarrow',[0.656171284634761 0.780856423173804],...
    [0.297148148148148 0.448148148148148],'String',{'O'},'FontWeight','bold',...
    'FontSize',24);

% Create textarrow
annotation(figure1,'textarrow',[0.829974811083123 0.769521410579345],...
    [0.846296296296296 0.772222222222222],'String',{'O^{8+}'},...
    'FontWeight','bold',...
    'FontSize',24);

% Create textarrow
annotation(figure1,'textarrow',[0.651133501259446 0.779596977329975],...
    [0.393444444444445 0.55],'String',{'O^-'},'FontWeight','bold','FontSize',24);

% Create textarrow
annotation(figure1,'textarrow',[0.604534005037783 0.734256926952141],...
    [0.447148148148149 0.611111111111111],'String',{'O^+'},'FontWeight','bold',...
    'FontSize',24);

