function XSPlot27(Parent1, dcdsI1, YMatrix1)
%CREATEAXES(Parent1, dcdsI1, YMatrix1)
%  PARENT1:  axes parent
%  DCDSI1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Jan-2018 11:53:15

% Create axes
axes1 = axes('Parent',Parent1);
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(dcdsI1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(loglog1(1),'DisplayName','O^{2+}','Color',[0 0 1]);
set(loglog1(2),'DisplayName','O^{3+}','Color',[1 0 0]);
set(loglog1(3),'DisplayName','O^{4+}','Color',[0 1 0]);
set(loglog1(4),'DisplayName','O^{5+}');
set(loglog1(5),'DisplayName','O^{6+}','Color',[1 0 1]);
set(loglog1(6),'DisplayName','O^{7+}','Color',[0 1 1]);

% Create ylabel
ylabel('Cross-Section [cm^{-2}]');

% Create xlabel
xlabel('Energy [keV/u]');

% Create title
title('Insert Process Here');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold','XMinorTick','on','XScale',...
    'log','YMinorTick','on','YScale','log','TickDir','both');
